# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [47]:
print(np.__version__)
np.show_config()

2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.30
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/opt/miniconda3/conda-bld/numpy_and_

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
A = np.zeros(10)
print(A)

#### 4. How to find the memory size of any array (★☆☆)

In [48]:
Z = np.zeros(10)
print(Z.nbytes)

80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
A = np.zeros(10)
A[4] = 1
print(A)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
A = np.arange(start=10,stop=50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
print(A[::-1])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [3]:
A = np.arange(start=0,stop=9)
A_new = A.reshape(3,3)
print(A_new)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [21]:
B = np.arange(6)
A = np.array([1,2,0,0,4,0])
print(B[A != 0])

np.nonzero(A)

[0 1 4]


(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [23]:
A = np.zeros(9)
A_new = A.reshape(3,3)
A_new[[0,1,2],[0,1,2]] = 1
print(A_new)

np.eye(3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [25]:
A = np.random.random((3,3,3))
print(A)

[[[0.07996157 0.21288146 0.93427607]
  [0.51162901 0.40661104 0.57734258]
  [0.29864099 0.31494512 0.98468833]]

 [[0.95801008 0.79530733 0.17159593]
  [0.8850233  0.58897034 0.46213498]
  [0.509434   0.78903962 0.57919766]]

 [[0.75291812 0.02451329 0.63172468]
  [0.93383352 0.35634444 0.01384374]
  [0.6151243  0.18161924 0.63899893]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [29]:
A = np.random.random((10,10))
print(A.min())
print(A.max())

0.0040755025695083935
0.9823026356203814


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [31]:
A = np.random.random(30)
print(A.mean())

0.4897288121520584


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [39]:
A = np.zeros(25)
A_new = A.reshape(5,5)
A_new[[0,4],:] = 1
A_new[:,[0,4]] = 1
print(A_new)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [40]:
A = np.zeros(25)
A_new = A.reshape(5,5)
A_new[1,0]=1
A_new[2,1]=2
A_new[3,2]=3
A_new[4,3]=4
print(A_new)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [42]:
A = np.zeros((8,8),dtype=int)
A[0::2,0::2]=1
A[1::2,1::2]=1
print(A)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [43]:
np.unravel_index(99,(6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [44]:
X = np.random.random((5,5))
Z = (X-X.mean())/X.std()
print(Z)

[[ 1.42710793 -0.44328629  1.49370508  0.23076169  1.19204562]
 [-1.21932667  1.82341903 -0.2685248  -0.17439978 -0.61643118]
 [ 0.20292788 -0.55909329 -0.40654233  0.49060414  1.36674862]
 [ 0.69471459 -0.75254831 -1.30291136 -1.44081508  0.16225023]
 [ 1.67277759 -0.48316578 -0.89572638 -1.25430445 -0.93998669]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [46]:
color = np.dtype([('R',np.ubyte),('G',np.ubyte),('B',np.ubyte),('A',np.ubyte)])
print(color)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
