#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [7]:
import numpy as np
A = np.arange(15)
A_new = A.reshape(5,3)
B = np.arange(6)
B_new = B.reshape(3,2)
res = np.dot(A_new,B_new)
print(res)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [8]:
Z = np.arange(11)
Z[(Z > 3) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [9]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1 # 잘못된코드
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [14]:
np.array(0) / np.array(0)

/var/folders/w6/fhx2fj2d3t717fvxsdxb48180000gn/T/ipykernel_28083/873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

In [15]:
np.array(0) // np.array(0)

/var/folders/w6/fhx2fj2d3t717fvxsdxb48180000gn/T/ipykernel_28083/2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


np.int64(0)

In [17]:
np.array([np.nan]).astype(int).astype(float)

/var/folders/w6/fhx2fj2d3t717fvxsdxb48180000gn/T/ipykernel_28083/699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([0.])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [18]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
np.intersect1d(Z1, Z2)

array([1, 4, 5, 6, 8])

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


In [19]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/w6/fhx2fj2d3t717fvxsdxb48180000gn/T/ipykernel_28083/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [20]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [21]:
A = np.ones(3)*1
B = np.ones(3)*2

np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

print(A)

[-1.5 -1.5 -1.5]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [23]:
Z = np.random.uniform(0, 10, 10)
print("원본:", Z)

print("방법1 (Z - Z%1):", Z - Z % 1)
print("방법2 (Z // 1):  ", Z // 1)

원본: [3.67546366 3.88301887 7.60829351 7.08745834 9.83846356 4.59102404
 1.73351193 6.32500149 9.36823334 8.26766843]
방법1 (Z - Z%1): [3. 3. 7. 7. 9. 4. 1. 6. 9. 8.]
방법2 (Z // 1):   [3. 3. 7. 7. 9. 4. 1. 6. 9. 8.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [24]:
Z = np.zeros((5, 5))    # shape (5, 5) — 아직 전부 0
v = np.arange(5)         # shape (5,)   — [0, 1, 2, 3, 4]

Z + v

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 32. Create a random vector of size 10 and sort it (★★☆)

In [25]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.15299136 0.21783441 0.24450484 0.30234447 0.30896498 0.31979648
 0.3323021  0.49701439 0.57876799 0.86206879]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [26]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A, B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [27]:
Z = np.random.random((10, 2))

x = Z[:, 0]
y = Z[:, 1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

polar = np.column_stack((r, theta))

print(polar)

[[0.55321696 0.1216929 ]
 [0.79128997 0.93509254]
 [0.90915638 0.29981594]
 [0.99088389 1.21029357]
 [0.66804366 0.85338814]
 [1.32305814 0.77144056]
 [0.86706607 0.51616337]
 [1.2107537  0.62444971]
 [0.94493072 0.38785507]
 [0.88372313 0.07832976]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [28]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.82851021 0.17882673 0.17606931 0.13479458 0.95644476 0.05172354
 0.47899431 0.91929275 0.93196995 0.46445998]
[0.82851021 0.17882673 0.17606931 0.13479458 0.         0.05172354
 0.47899431 0.91929275 0.93196995 0.46445998]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [29]:
Z = np.arange(100)
v = np.random.uniform(0,100)
dist = (np.abs(Z-v)).argmin()
print(Z[dist]) 

77


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [30]:
import numpy as np
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [3]:
n = 5   # 2D 배열의 크기 (원하는 정수로)
p = 3   # 배치할 원소 개수 (n*n보다 작아야 함)
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False), 1)  # 1 자리에 원하는 값
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [1]:
import numpy as np

In [35]:
Z = np.random.randint(0,10,(3,3))
Z[:, 0]
order = Z[:, 0].argsort()
Z_sorted = Z[order]
print(Z_sorted)

[[8 7 7]
 [9 3 1]
 [9 8 8]]


In [36]:
Z[:, 1]
order = Z[:, 1].argsort()
Z_sorted = Z[order]
print(Z_sorted)

[[9 3 1]
 [8 7 7]
 [9 8 8]]


In [37]:
Z[:, 2]
order = Z[:, 2].argsort()
Z_sorted = Z[order]
print(Z_sorted)

[[9 3 1]
 [8 7 7]
 [9 8 8]]
